#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifeq ($(AGOLD_CAMERA_VERSION),yes)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/agold_cam_version
endif

obj-y += ov5670mipi_Sensor.o 
#obj-y += ov5670_otp.o


