#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifeq ($(CONFIG_MTK_CAMERA_VERSION),y)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cam_version
endif

obj-y += ov5670mipi_Sensor.o
#obj-y += ov5670_otp.o

