#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifeq ($(CONFIG_MTK_CAMERA_VERSION),y)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cam_version
endif

obj-y += ov13853mipiraw_Sensor.o
obj-y += ov13853_otp_pdaf.o
#obj-y += ov13853_otp_cal.o

