#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ifeq ($(CONFIG_MTK_CAMERA_VERSION),y)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cam_version
endif

obj-y += s5k3l8mipiraw_Sensor.o s5k3l8_eeprom.o
#obj-y += s5k3l8mipiraw_pdaf.o

