# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   +=  temperature.o temperature_factory.o

obj-$(CONFIG_MTK_HSHCAL002) += hshcal002/

