#include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom
ifeq ($(CONFIG_MTK_CAMERA_VERSION),y)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cam_version
endif
obj-y += gc5025mipi_Sensor.o

