include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/src/$(MTK_PLATFORM)

obj-$(CONFIG_MTK_CAMERA_VERSION) += agold_cam_version.o
obj-$(CONFIG_MTK_CAMERA_VERSION) += agold_camera_info.o
obj-$(CONFIG_MTK_CAMERA_VERSION) += agold_hw_compatible.o

